[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-vst-string]
path = "../aloe-vst-string"
[dependencies.aloe-vst-types]
path = "../aloe-vst-types"
[package]
edition = "2021"
name = "aloe-vst-plugin"
version = "0.1.0"
