[dependencies]
freetype-rs = "*"
[dependencies.aloe-array]
path = "../aloe-array"
[dependencies.aloe-colour]
path = "../aloe-colour"
[dependencies.aloe-container]
path = "../aloe-container"
[dependencies.aloe-critical-section]
path = "../aloe-critical-section"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-events]
path = "../aloe-events"
[dependencies.aloe-files]
path = "../aloe-files"
[dependencies.aloe-geometry]
path = "../aloe-geometry"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-memory]
path = "../aloe-memory"
[dependencies.aloe-xml]
path = "../aloe-xml"
[package]
edition = "2021"
name = "aloe-font"
version = "0.1.0"
