[dependencies]
atomic = "*"
bitfield = "*"
lazy_static = "*"
libc = "*"
modular-bitfield = "*"
num = "*"
parking_lot = "*"
static_assertions = "*"
wchar = "*"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-files]
path = "../aloe-files"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-memory]
path = "../aloe-memory"
[dependencies.aloe-text]
path = "../aloe-text"
[package]
edition = "2021"
name = "aloe-streams"
version = "0.1.0"