[dependencies.aloe-component]
path = "../aloe-component"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-events]
path = "../aloe-events"
[dependencies.aloe-font]
path = "../aloe-font"
[dependencies.aloe-geometry]
path = "../aloe-geometry"
[dependencies.aloe-graphics]
path = "../aloe-graphics"
[dependencies.aloe-deps]
path = "../aloe-deps"
[package]
edition = "2021"
name = "aloe-bubble"
version = "0.1.0"