[dependencies]
atomic = "*"
bitfield = "*"
lazy_static = "*"
libc = "*"
modular-bitfield = "*"
num = "*"
parking_lot = "*"
static_assertions = "*"
wchar = "*"
[dependencies.aloe-buffers]
path = "../aloe-buffers"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-oboe-audio-loader]
path = "../aloe-oboe-audio-loader"
[dependencies.aloe-oboe-audioclock]
path = "../aloe-oboe-audioclock"
[dependencies.aloe-oboe-audioio]
path = "../aloe-oboe-audioio"
[dependencies.aloe-oboe-core]
path = "../aloe-oboe-core"
[dependencies.aloe-oboe-counters]
path = "../aloe-oboe-counters"
[dependencies.aloe-oboe-devicequirks]
path = "../aloe-oboe-devicequirks"
[dependencies.aloe-oboe-extensions]
path = "../aloe-oboe-extensions"
[dependencies.aloe-oboe-fifo]
path = "../aloe-oboe-fifo"
[dependencies.aloe-oboe-fixedblockrw]
path = "../aloe-oboe-fixedblockrw"
[dependencies.aloe-oboe-flowgraph]
path = "../aloe-oboe-flowgraph"
[dependencies.aloe-oboe-flowgraph-converter]
path = "../aloe-oboe-flowgraph-converter"
[dependencies.aloe-oboe-flowgraph-filter]
path = "../aloe-oboe-flowgraph-filter"
[dependencies.aloe-oboe-flowgraph-node]
path = "../aloe-oboe-flowgraph-node"
[dependencies.aloe-oboe-flowgraph-resampler]
path = "../aloe-oboe-flowgraph-resampler"
[dependencies.aloe-oboe-flowgraph-sink]
path = "../aloe-oboe-flowgraph-sink"
[dependencies.aloe-oboe-flowgraph-source]
path = "../aloe-oboe-flowgraph-source"
[dependencies.aloe-oboe-latencytuner]
path = "../aloe-oboe-latencytuner"
[dependencies.aloe-oboe-no-aaudio]
path = "../aloe-oboe-no-aaudio"
[dependencies.aloe-oboe-session]
path = "../aloe-oboe-session"
[dependencies.aloe-oboe-sles]
path = "../aloe-oboe-sles"
[dependencies.aloe-oboe-sourcefloatcaller]
path = "../aloe-oboe-sourcefloatcaller"
[dependencies.aloe-oboe-stream]
path = "../aloe-oboe-stream"
[dependencies.aloe-oboe-trace]
path = "../aloe-oboe-trace"
[package]
authors = [ "klebs <tpk3.mx@gmail.com>" ]
categories = [ "gui", "graphics", "hardware-support" ]
description = "Oboe-based audio I/O for Android with low-latency features -- see JUCE's Oboe integration approach."
documentation = "https://docs.rs/aloe-oboe"
edition = "2024"
keywords = [ "juce", "audio", "gui", "graphics", "listener" ]
license = "GPL-3.0"
metadata.cpp-authors = [ "Adam <blekk2@gmail.com>", "Aga Janowicz <aga@roli.com>", "Agnieszka Janowicz <agnieszka.janowicz@roli.com>", "Alain Martin <amartin@keytrol.org>", "Anthony Nicholls <anthony@juce.com>", "Attila Szarvas <attila@juce.com>", "Cesare Ferrari <cesare@loftsoft.co.uk>", "Christian Haase <chrhaase@outlook.dk>", "Christopher Fonseka <chris.fonseka@googlemail.com>", "Dan Raviv <dan@soundradix.com>", "Daniel Walz <daniel.walz@roli.com>", "Dimitri Sudell <dimitri.sudell@roli.com>", "Fabian Renn-Giles <fabian@fielding.dev, fabian@roli.com>", "Felipe F. Tonello <felipe.tonello@roli.com>", "Felix Faire <felixfaire@gmail.com>", "Ian Clarkson <clarksonian@gmail.com>", "Ivan COHEN <ivan.cohen@musicalentropy.com>", "Ivan Cohen <ivan.cohen@musicalentropy.com>", "James Hurst <james@pintsized.co.uk>", "James Johnson <james.johnson@focusrite.com>", "Joshua Gerrard <joshua.gerrard@roli.com>", "Julian Storer <jules@BigMac.local, jules@bigmac.home, jules@rawmaterialsoftware.com>", "Leigh Marble <tech@laughing-stock.org>", "Lukasz Kozakiewicz <lukasz.kozakiewicz@roli.com>", "Mathieu Demange <contact@mathieudemange.fr>", "Matt Gonzalez <matt@echoaudio.com>", "Mike Toon <michael.toon@roli.com>", "Nathan Blair <nathan@mat.ucsb.edu>", "Noah Dayan <noahdayan@gmail.com>", "Oli <oli@juce.com>", "Oli James <oli@juce.com>", "Oliver James <oli@juce.com>", "Paul Gration <pmgration@gmail.com>", "Rachel <rachel@ROLIs-iMac.local>", "Rachel Susser <rachel.susser@roli.com>", "Reuben Thomas <reuk@users.noreply.github.com>", "Richard Meyer <richard@roli.com>", "Roland Rabien <figbug@gmail.com>", "Steve Lhomme <robux4@ycbcr.xyz>", "Tatsuya Shiozawa <shio.tatsu99@gmail.com>", "Timur Doumler <timur@roli.com>", "Tom Duncalf <tom@tomduncalf.com>", "Tom Maisey <tom.maisey@roli.com, tommaisey@gmail.com>", "Tom Poole <thomas.poole@roli.com, tom@juce.com>", "Tom Waldron <tom@roli.com>", "XmasRights <chris.fonseka@googlemail.com>", "Yuki <68385758+YukiChiyoda@users.noreply.github.com>", "Zsolt Garamvolgyi <zsolt@roli.com>", "attila <attila@juce.com>", "cesare <cesare.ferrari@gmail.com, cesare@loftsoft.co.uk>", "chroma <oli@chromalabs.co.uk>", "dimitri <dimitri.sudell@roli.com>", "dimitriroli <dimitri.sudell@roli.com>", "ed <ed_davies95@hotmail.co.uk, eddavies95@gmail.com>", "fieldingfabian <fabian@fielding.dev>", "fr810 <fr810@DESKTOP-JGTHN1K>", "hogliux <fabian.renn@gmail.com>", "juce-team <juce-team@dtk-office.local>", "jules <jules@juce.com, jules@rawmaterialsoftware.com, julianstorer@gmail.com>", "luigisambuy <lsambuy@stanford.edu>", "luz paz <luzpaz@pm.me>", "luzpaz <luzpaz@users.noreply.github.com>", "martin@ncore.li <martin@ncore.li>", "michael.toon <michael.toon@roli.com>", "miketoon <32300092+miketoon@users.noreply.github.com, michael.toon@roli.com>", "reuk <reuk@stretch, reuk@users.noreply.github.com, reuk@users.roreply.github.com>", "stefan <stefan.graenitz@gmail.com>", "stefan.graenitz <stefan.graenitz@gmail.com>", "tommaisey <tom.maisey@roli.com>", "tpoole <872729+tpoole@users.noreply.github.com, t.b.poole@gmail.com, thomas.poole@roli.com, tom@juce.com, tom@tp-mbp.local>", "無常 <3142324836@qq.com>" ]
metadata.original-repo = "https://github.com/juce-framework/JUCE"
name = "aloe-oboe"
readme = "README.md"
repository = "https://github.com/klebs6/aloe-rs"
version = "0.1.0"
