[dependencies.aloe-au-imports]
path = "../aloe-au-imports"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-deps]
path = "../aloe-deps"
[package]
edition = "2021"
name = "aloe-au-debug"
version = "0.1.0"