[dependencies.aloe-colour]
path = "../aloe-colour"
[dependencies.aloe-component]
path = "../aloe-component"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-documentwindow]
path = "../aloe-documentwindow"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-keyboard]
path = "../aloe-keyboard"
[dependencies.aloe-memory]
path = "../aloe-memory"
[package]
edition = "2021"
name = "aloe-dialogwindow"
version = "0.1.0"