[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-vst-stream]
path = "../aloe-vst-stream"
[dependencies.aloe-vst-types]
path = "../aloe-vst-types"
[package]
edition = "2021"
name = "aloe-vst-attributes"
version = "0.1.0"