[dependencies]
atomic = "*"
bitfield = "*"
lazy_static = "*"
libc = "*"
modular-bitfield = "*"
num = "*"
parking_lot = "*"
static_assertions = "*"
wchar = "*"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-sample-type]
path = "../aloe-sample-type"
[dependencies.aloe-smoothed-value]
path = "../aloe-smoothed-value"
[package]
edition = "2021"
name = "aloe-panner"
version = "0.1.0"